version: "1.0"
   
services:
  test_db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
  test_web:
    build:
      context: ../../
      dockerfile: ./docker/test-flask/dockerfile
    command: flask run
    volumes:
      - ../../test-flask/:/usr/src/test-flask/
    ports:
      - "3001:3001"
    expose:
      - 3001
    environment:
      # Flask
      - FLASK_RUN_PORT=3001
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # PostgreSQL DB
      - POSTGRES_DB=test_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=test_db
      - POSTGRES_PORT=5432
    depends_on:
      - test_db
    stdin_open: true
    tty: true

volumes:
  postgres_data: